version: '3.8'

services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "52773:52773" # Web Server port
    volumes:
      - ./web:/usr/irissys/csp/websocket
    command: --check-caps false

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - iris

